[package]
name = "conch-cookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conch-jce = { path = "src/network/protocol/frame/jce" }
bytes = "1.1.0"
futures = "0.3.21"
reqwest = "0.11.11"
tokio = { version = "1.20.0", features = ["full"] }
