[package]
name = "conch-cookie"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jce = { path = "src/network/protocol/frame/jce", package = "cookie-jce" }
anyhow = "1.0.61"
bytes = "1.2.1"
reqwest = "0.11.11"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
