version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️cargo "

  - package-ecosystem: "gomod"
    directory: "/cookie/network/protocol/jce/generator"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️gomod "

  - package-ecosystem: "gomod"
    directory: "/actions/stepper"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️gomod "

  - package-ecosystem: "pub"
    directory: "/dashboard"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️pub "

  - package-ecosystem: "npm"
    directory: "/manual"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️yarn "

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    reviewers: [ "qianjunakasumi" ]
    assignees: [ "qianjunakasumi" ]
    open-pull-requests-limit: 114
    rebase-strategy: "disabled"
    commit-message:
      prefix: "pref⬆️action "
