[package]
name = "senjuko-conch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "conch"
path = "crates/conch/main.rs"

[workspace]
members = [
    "crates/cookie",
    "crates/cookie/cipher/qtea",
    "crates/cookie/network/protocol/frame/jce",

    "crates/macaron"
]

[dependencies]
conch-cookie = { path = "crates/cookie" }
