[package]
name = "senjuko-conch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "conch"
path = "crates/conch/main.rs"

[workspace]
members = [
    "crates/cookie",
    "crates/cookie/cipher/qtea",
    "crates/cookie/network/protocol/jce/frame",
    "crates/macaron"
]

[dependencies]
cookie = { path = "crates/cookie", package = "conch-cookie" }
macaron = { path = "crates/macaron", package = "conch-macaron" }
anyhow = "1.0.62"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
