[package]
name = "conch-tool"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "conch-tool"
path = "main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive", "cargo", "wrap_help", "env"] }