name: Updatable check

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: tibdex/github-app-token@v1
        name: Generate token
        id: generate-token
        with:
          app_id: 242446
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update version
        id: update-version
        working-directory: ./actions/crow
        run: |
          go run -v ./...
          echo "newVer=$(cat ../temp/ci.version)" >> $GITHUB_OUTPUT
          echo "oldVer=$(cat ../temp/curr.version)" >> $GITHUB_OUTPUT
          echo "fileName=$(cat ../temp/file.name)" >> $GITHUB_OUTPUT
          echo "url=$(cat ../temp/url)" >> $GITHUB_OUTPUT

      - name: Create Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          filename: actions/issue-template/update-from-upstream.md
          update_existing: true
          search_existing: all
